= calcnumpp

This is a test repository for implementing  different mathematical alogithms.

It is not a generic library like http://arma.sourceforge.net/[Armadillo] or http://blitz.sourceforge.net/[Blitz++].
It is a partial rewrite of algorithms I had to implement in C and Octave during university for various numerical courses.

I plan to implement different algorithm, the roadmap will probably be the following:

 - solving the root problems for nonlinear equations (bisection, Newton, and some of its variations)
 - algorithms and structures for managing polynomials and approximate functions through polynomials (interpolation)
 - managing matrices and solving linear equations
 - some basic algorithms for solving Cauchy problems, like Euler or Runge-Kutta methods
 - other algorithms for solving ODE problems, like Adams method


More informations can be found at https://fekir.info/categories/floating-in-c++/.

I hope that this project can help math students to implement theyr own

The code should be easy to read and use.
The project is structured with https://cmake.org/[CMake], with most compiler warnings enabled.

By using an IDE like https://en.wikipedia.org/wiki/Qt_Creator[Qt Creator], that also provides an easy-to use frontend for debugging, I hope that this project may help other students.
Inspecting the variables during runtime, eases the process of debugging a lot.
